run:
  concurrency: 5
  skip-dirs:
    - vendor
  tests: true
  go: '1.19'

issues:
  exclude-use-default: false
  exclude:
    - ST1000
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - paralleltest

linters:
  enable-all: true
  disable:
    # Not suitable for this package
    - wrapcheck
    - gci
    - gochecknoglobals
    - gomoddirectives
    - goerr113

    # Deprecated
    - maligned
    - interfacer
    - golint
    - scopelint
    - exhaustivestruct
